src/Entity/Pokemon.php
<?php

namespace App\Entity;

use App\Repository\PokemonRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PokemonRepository::class)]
class Pokemon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El nombre es obligatorio')]
    private ?string $nombre = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'El numero es obligatorio')]
    private ?int $numero = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El tipo es obligatorio')]
    private ?string $Tipo = null;

    #[ORM\ManyToOne(inversedBy: 'pokemon')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Region $Region = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(?int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->Tipo;
    }

    public function setTipo(?string $Tipo): self
    {
        $this->Tipo = $Tipo;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->Region;
    }

    public function setRegion(?Region $Region): static
    {
        $this->Region = $Region;

        return $this;
    }
}

templates/partials/datos_pokemons.html.twig
<ul>
    <li><strong>{{pokemon.nombre}}</strong></li>
    <li><strong>Numero</strong>: {{pokemon.numero}}</li>
    {% if pokemon.region %}
    <li><stron>Region: </strong>{{pokemon.region.nombre}}</li>
    {% endif %}
    <li><strong>Tipo</strong>: {{pokemon.Tipo}}</li>
    <a href='/pokedex/editar/{{pokemon.numero}}'>Modificar</a>
    <a href='/pokedex/delete/{{pokemon.numero}}'>Borrar</a>
</ul>